### ISSUE TITLE
Implement Windows Imaging Component?

### ISSUE THREAD

**Issue by saschanaz** [saschanaz/jxl-winthumb#8]
... and ulimately split it out as a separate library for other codecs.

Nobody outside Microsoft knows its future but it seems it can still be useful, as Windows Photo Gallery still exists as a legacy-like component inside Windows.

I hoped browsers implementations could fulfill the need for viewers, but sadly that's not expected to happen soon.

**Comment by eddiezato** [comment]
The updated JXL WIC is very much needed, not because Windows Photo Gallery is out there, but because there are many other useful viewers that can support new image formats through the WIC. For example, [JPEGView](https://sourceforge.net/projects/jpegview/) and [NeeView](https://bitbucket.org/neelabo/neeview/wiki/Home).

**Comment by eddiezato** [comment]
Thank you! 👍
